namespace: rcx_one
name: linkoverlay
version: 1.0.0

readme: README.md

authors:
- Eike <ansible@rcx.one>


description: This collection enables the management of directories and the creation of a symlink overlays from these directories onto other directory trees.

# L(SPDX,https://spdx.org/licenses/) licenses
license:
- GPL-3.0-or-later

tags: [dotfiles, filesync, overlay]

dependencies: {}

repository: https://git.rcx.one/eike/linkoverlay
documentation: https://git.rcx.one/eike/linkoverlay
homepage: https://git.rcx.one/eike/linkoverlay
issues: https://git.rcx.one/eike/linkoverlay

# A list of file glob-like patterns used to filter any files or directories that should not be included in the build
# artifact. A pattern is matched from the relative path of the file or directory of the collection directory. This
# uses 'fnmatch' to match the files or directories. Some directories and files like 'galaxy.yml', '*.pyc', '*.retry',
# and '.git' are always filtered. Mutually exclusive with 'manifest'
build_ignore: [gen_docs.py]

# A dict controlling use of manifest directives used in building the collection artifact. The key 'directives' is a
# list of MANIFEST.in style
# L(directives,https://packaging.python.org/en/latest/guides/using-manifest-in/#manifest-in-commands). The key
# 'omit_default_directives' is a boolean that controls whether the default directives are used. Mutually exclusive
# with 'build_ignore'
# manifest: null
