---
- name: Record result of single task
  ansible.builtin.lineinfile:
    path: "{{ journal_path }}"
    line: "{{ result.dest | default(result.path | default('!path argument is missing for task')) }}"
  when: result is not contains("results") and result is not skipped and result is not failed
  delegate_to: localhost

- name: Record results of loop task
  ansible.builtin.lineinfile:
    path: "{{ journal_path }}"
    line: "{{ item.dest | default(item.path | default('!path argument is missing for item')) }}"
  when: item is not skipped and item is not failed
  loop: "{{ result.results | default([]) }}"
  delegate_to: localhost
